---
users:
  - name: "{{ lookup('env', 'CLUSTER_NAME') }}"
    uid: 1100
    # Password created with `mkpasswd --method=SHA-512 pass1234`
    password: $6$6/6NkDn01w$6ld/sdc/B42cVtSNFQTQLlNPYOqin8m4kluy.QbvtLraHLliTs5QaPIYJcKyYr7KKhsY2znFZLSC2YzdROKwZ.
    # Also add roles/common/files/<username>.key and roles/common/files/<username>.key.pub
    # with ssh-keygen -f roles/common/files/<username>.key

trusted_networks:
  - 10.100.107.0/8
  - 192.168.1.1/16
  - 172.17.0.1/24

python_packages:

system_packages:
  - aptitude

create_swap_space: false

#Define the JAVA_HOME (default: "/usr/lib/jvm/default-java")
java_home: "/usr/lib/jvm/default-java"

emma_modules_dir: "/data/local/{{ lookup('env', 'CLUSTER_NAME') }}/modules"
