---
- name: Allow SSH in UFW
  ufw: rule=allow port=22 proto=tcp
- name: Set firewall default policy
  ufw: state=enabled policy=reject
  sudo: true
- name: Only allow incoming traffic from trusted networks
  ufw: rule=allow src={{ item }} state=enabled
  with_items: "{{ trusted_networks }}"

